# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Akilarの糖果屋
subtitle: Akilar.top
description: 流水幽吟绕耳边，<br>煦风馨语抚心弦，<br>挥臂欲揽冰钩月，<br>银星斟酌醉人涎。
keywords: diary; experience; tutorial;
author: Akilar
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'https://yoursite.com/child' and root as '/child/'
url: https://akilar.top
root: /
permalink_defaults:
permalink: posts/:abbrlink/  # 此处可以自己设置，也可以直接使用 :/abbrlink
abbrlink:
  alg: crc32   #算法： crc16(default) and crc32
  rep: hex     #进制： dec(default) and hex
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date

archive_generator:
  per_page: 30 ##归档页面默认30篇文章标题
  yearly: true  ##生成年视图
  monthly: true ##生成月视图

tag_generator:
  per_page: 10

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ark

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:Akilarlxh/Akilarlxh.github.io.git



# APlayer
# https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer:
  meting: true
  asset_inject: false


# local_search
# search:
#   path: search.xml
#   field: post
#   content: true
# algolia search
algolia:
  appId: 
  apiKey: 
  adminApiKey: 
  chunkSize: 5000
  indexName: 
  fields:
    - content:strip:truncate,0,500
    - path
    - title
  plugins:
    - hexo-algoliasearch

# # KaTeX
# markdown_it_plus:
#   plugins:
#     - plugin:
#       name: '@neilsustc/markdown-it-katex'
#       enable: true
#       options:
#         strict: false
# hexo-renderer-kramed
## Docs: https://www.npmjs.com/package/hexo-renderer-kramed
kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
# hexo-generator-feed
# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 5

# hexo-generator-sitemap
sitemap:
  path: sitemap.xml
# hexo-generator-baidu-sitemap
baidusitemap:
  path: baidusitemap.xml
# hexo-filter-nofollow
nofollow:
  enable: true
  field: site
  exclude:
    - 'akilarlxh.github.io'
    - 'akilar.top'
    - 'akilar.gitee.io'
    - 'blog.akilar.top'
    - 'icp.gov.moe'
    - 'www.upyun.com'
    - 'beian.miit.gov.cn'

# https://www.npmjs.com/package/hexo-blog-encrypt-customized
# 文章加密
# Security
# hexo-blog-encrypt
encrypt:
  enable: true
  silent: true
  abstract: Here's something encrypted, password is required to continue reading.
  message: Hey, password is required here.
  tags:
  - {name: encryptAsDiary, password: passwordA}
  - {name: encryptAsTips, password: passwordB}
  theme: xray
  wrong_pass_message: Oh, this is an invalid password. Check and try again, please.
  wrong_hash_message: Oh, these decrypted content cannot be verified, but you can still have a look.

# 随机跳转
random:
  path: # 随机链接路径，默认"random/index.html"


